---
version: '3'
services:
  elasticsearch:
    image: elastic/elasticsearch:6.0.1
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - 9200:9200

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  cassandra:
    image: cassandra:3.9
    environment:
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
    ports:
      - 9042:9042

  metrictank:
    hostname: metrictank
    image: grafana/metrictank
    ports:
      - 2003:2003
    expose:
      - 6060
    environment:
      WAIT_HOSTS: cassandra:9042,kafka:9092
      WAIT_TIMEOUT: 60
      MT_HTTP_MULTI_TENANT: "false"

  graphite:
    image: raintank/graphite-mt
    expose:
      - 80
    environment:
      GRAPHITE_CLUSTER_SERVERS: metrictank:6060
      GRAPHITE_STATSD_HOST: statsdaemon
      SINGLE_TENANT: "1"
      WSGI_PROCESSES: 4
      WSGI_THREADS: 25

  statsdaemon:
    image: raintank/statsdaemon
    ports:
      - 8125:8125/udp
    volumes:
      - ./cfg/statsdaemon.ini:/etc/statsdaemon.ini

  pitchfork:
    image: hotelsdotcom/pitchfork:1.5
    ports:
      - 18080:8080
      - 9411:9411
    environment:
      PITCHFORK_FORWARDERS_HAYSTACK_KAFKA_ENABLED: "true"
      PITCHFORK_FORWARDERS_HAYSTACK_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
